# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - tech0-gen-9-step3-1-node-50

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
      #1
        env:
          NEXT_PUBLIC_API_ENDPOINT: ${{ secrets.NEXT_PUBLIC_API_ENDPOINT }}
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
      #2
      - name: Copy artifact for deployment job
        run: |
          mkdir deploy
          cp -r ./.next/standalone/. ./deploy
          cp -r ./.next/static/. ./deploy/.next/static

      - name: Zip artifact for deployment
        run: zip release.zip ./deploy -r #3

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'tech0-gen-9-step3-1-node-50'
          slot-name: 'Production'
          package: ./deploy #4
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6684294CFFD14CBE934D078BCB6715CF }}